version: '3.8'

services:
  movie-fixer:
    build: .
    ports:
      - "8096:8096"  # Host Port : Container Port
    environment:
      - ENV=production
    volumes:
      - .:/app  # Optional for development, syncs local files with the container
